/*
 * generated by Xtext 2.19.0
 */
package src.idm_mml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("src/idm_mml/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
