/*
 * generated by Xtext 2.19.0
 */
package src.idm_mml.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import src.idm_mml.MyDslRuntimeModule
import src.idm_mml.MyDslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyDslIdeSetup extends MyDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule, new MyDslIdeModule))
	}
	
}
