/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import src.idm_mml.mML.Cible;
import src.idm_mml.mML.MMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cible</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CibleImpl extends MinimalEObjectImpl.Container implements Cible
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CibleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MMLPackage.Literals.CIBLE;
  }

} //CibleImpl
