/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import src.idm_mml.mML.MMLPackage;
import src.idm_mml.mML.Predictives;
import src.idm_mml.mML.idColonne;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Predictives</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.impl.PredictivesImpl#getPredictives <em>Predictives</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PredictivesImpl extends MinimalEObjectImpl.Container implements Predictives
{
  /**
   * The cached value of the '{@link #getPredictives() <em>Predictives</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredictives()
   * @generated
   * @ordered
   */
  protected EList<idColonne> predictives;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PredictivesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MMLPackage.Literals.PREDICTIVES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<idColonne> getPredictives()
  {
    if (predictives == null)
    {
      predictives = new EObjectContainmentEList<idColonne>(idColonne.class, this, MMLPackage.PREDICTIVES__PREDICTIVES);
    }
    return predictives;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MMLPackage.PREDICTIVES__PREDICTIVES:
        return ((InternalEList<?>)getPredictives()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MMLPackage.PREDICTIVES__PREDICTIVES:
        return getPredictives();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MMLPackage.PREDICTIVES__PREDICTIVES:
        getPredictives().clear();
        getPredictives().addAll((Collection<? extends idColonne>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MMLPackage.PREDICTIVES__PREDICTIVES:
        getPredictives().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MMLPackage.PREDICTIVES__PREDICTIVES:
        return predictives != null && !predictives.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //PredictivesImpl
