/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import src.idm_mml.mML.MMLPackage;
import src.idm_mml.mML.Strategie;
import src.idm_mml.mML.Validation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Strategie</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.impl.StrategieImpl#getStrategie <em>Strategie</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StrategieImpl extends MinimalEObjectImpl.Container implements Strategie
{
  /**
   * The cached value of the '{@link #getStrategie() <em>Strategie</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrategie()
   * @generated
   * @ordered
   */
  protected EList<Validation> strategie;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StrategieImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MMLPackage.Literals.STRATEGIE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Validation> getStrategie()
  {
    if (strategie == null)
    {
      strategie = new EObjectContainmentEList<Validation>(Validation.class, this, MMLPackage.STRATEGIE__STRATEGIE);
    }
    return strategie;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MMLPackage.STRATEGIE__STRATEGIE:
        return ((InternalEList<?>)getStrategie()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MMLPackage.STRATEGIE__STRATEGIE:
        return getStrategie();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MMLPackage.STRATEGIE__STRATEGIE:
        getStrategie().clear();
        getStrategie().addAll((Collection<? extends Validation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MMLPackage.STRATEGIE__STRATEGIE:
        getStrategie().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MMLPackage.STRATEGIE__STRATEGIE:
        return strategie != null && !strategie.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //StrategieImpl
