/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.ide;

import src.idm_mml.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
