/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import src.idm_mml.ui.AbstractMyDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyDslUiModule extends AbstractMyDslUiModule {
  public MyDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
