/*
 * generated by Xtext 2.19.0
 */
package src.idm_mml.ui.tests;

import com.google.inject.Injector;
import idm_mml.ui.internal.Idm_mmlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Idm_mmlActivator.getInstance().getInjector("src.idm_mml.MyDsl");
	}

}
