/*
 * generated by Xtext 2.19.0
 */
package src.idm_mml.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MMLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.MML");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMMLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMmlAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMmlImplementationParserRuleCall_2_0 = (RuleCall)cMmlAssignment_2.eContents().get(0);
		private final Assignment cMmlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMmlDatasetParserRuleCall_3_0 = (RuleCall)cMmlAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MML:
		//	'MML' '{'
		//	mml+=Implementation+
		//	mml+=Dataset+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'MML' '{' mml+=Implementation+ mml+=Dataset+ '}'
		public Group getGroup() { return cGroup; }
		
		//'MML'
		public Keyword getMMLKeyword_0() { return cMMLKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//mml+=Implementation+
		public Assignment getMmlAssignment_2() { return cMmlAssignment_2; }
		
		//Implementation
		public RuleCall getMmlImplementationParserRuleCall_2_0() { return cMmlImplementationParserRuleCall_2_0; }
		
		//mml+=Dataset+
		public Assignment getMmlAssignment_3() { return cMmlAssignment_3; }
		
		//Dataset
		public RuleCall getMmlDatasetParserRuleCall_3_0() { return cMmlDatasetParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ImplementationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Implementation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cImplementationAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cImplementationKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Keyword cScikitLearnKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cWekaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cAlgoAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cAlgoAlgorithmeParserRuleCall_1_2_0 = (RuleCall)cAlgoAssignment_1_2.eContents().get(0);
		private final Assignment cMetriqueAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cMetriqueMetriqueParserRuleCall_1_3_0 = (RuleCall)cMetriqueAssignment_1_3.eContents().get(0);
		private final Assignment cStrategieAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cStrategieStrategieParserRuleCall_1_4_0 = (RuleCall)cStrategieAssignment_1_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_5 = (Keyword)cGroup_1.eContents().get(5);
		
		//Implementation:
		//	{Implementation} 'Implementation' 'Scikit-learn' | 'Weka' '{'
		//	algo+=Algorithme
		//	metrique+=Metrique
		//	strategie+=Strategie
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Implementation} 'Implementation' 'Scikit-learn' | 'Weka' '{' algo+=Algorithme metrique+=Metrique strategie+=Strategie
		//'}'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Implementation} 'Implementation' 'Scikit-learn'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Implementation}
		public Action getImplementationAction_0_0() { return cImplementationAction_0_0; }
		
		//'Implementation'
		public Keyword getImplementationKeyword_0_1() { return cImplementationKeyword_0_1; }
		
		//'Scikit-learn'
		public Keyword getScikitLearnKeyword_0_2() { return cScikitLearnKeyword_0_2; }
		
		//'Weka' '{' algo+=Algorithme metrique+=Metrique strategie+=Strategie '}'
		public Group getGroup_1() { return cGroup_1; }
		
		//'Weka'
		public Keyword getWekaKeyword_1_0() { return cWekaKeyword_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_1() { return cLeftCurlyBracketKeyword_1_1; }
		
		//algo+=Algorithme
		public Assignment getAlgoAssignment_1_2() { return cAlgoAssignment_1_2; }
		
		//Algorithme
		public RuleCall getAlgoAlgorithmeParserRuleCall_1_2_0() { return cAlgoAlgorithmeParserRuleCall_1_2_0; }
		
		//metrique+=Metrique
		public Assignment getMetriqueAssignment_1_3() { return cMetriqueAssignment_1_3; }
		
		//Metrique
		public RuleCall getMetriqueMetriqueParserRuleCall_1_3_0() { return cMetriqueMetriqueParserRuleCall_1_3_0; }
		
		//strategie+=Strategie
		public Assignment getStrategieAssignment_1_4() { return cStrategieAssignment_1_4; }
		
		//Strategie
		public RuleCall getStrategieStrategieParserRuleCall_1_4_0() { return cStrategieStrategieParserRuleCall_1_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_5() { return cRightCurlyBracketKeyword_1_5; }
	}
	public class DatasetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Dataset");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDatasetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPathAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPathSTRINGTerminalRuleCall_1_0 = (RuleCall)cPathAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCibleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCibleCibleParserRuleCall_3_0 = (RuleCall)cCibleAssignment_3.eContents().get(0);
		private final Assignment cPredictivesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPredictivesPredictivesParserRuleCall_4_0 = (RuleCall)cPredictivesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Dataset:
		//	'Dataset' path=STRING '{'
		//	cible+=Cible
		//	predictives+=Predictives
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Dataset' path=STRING '{' cible+=Cible predictives+=Predictives '}'
		public Group getGroup() { return cGroup; }
		
		//'Dataset'
		public Keyword getDatasetKeyword_0() { return cDatasetKeyword_0; }
		
		//path=STRING
		public Assignment getPathAssignment_1() { return cPathAssignment_1; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_1_0() { return cPathSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//cible+=Cible
		public Assignment getCibleAssignment_3() { return cCibleAssignment_3; }
		
		//Cible
		public RuleCall getCibleCibleParserRuleCall_3_0() { return cCibleCibleParserRuleCall_3_0; }
		
		//predictives+=Predictives
		public Assignment getPredictivesAssignment_4() { return cPredictivesAssignment_4; }
		
		//Predictives
		public RuleCall getPredictivesPredictivesParserRuleCall_4_0() { return cPredictivesPredictivesParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class StrategieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Strategie");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cStrategieKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cStrategieAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cStrategieValidationParserRuleCall_0_1_0 = (RuleCall)cStrategieAssignment_0_1.eContents().get(0);
		private final RuleCall cCrossValidationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Strategie:
		//	'Strategie' strategie+=Validation | CrossValidation;
		@Override public ParserRule getRule() { return rule; }
		
		//'Strategie' strategie+=Validation | CrossValidation
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'Strategie' strategie+=Validation
		public Group getGroup_0() { return cGroup_0; }
		
		//'Strategie'
		public Keyword getStrategieKeyword_0_0() { return cStrategieKeyword_0_0; }
		
		//strategie+=Validation
		public Assignment getStrategieAssignment_0_1() { return cStrategieAssignment_0_1; }
		
		//Validation
		public RuleCall getStrategieValidationParserRuleCall_0_1_0() { return cStrategieValidationParserRuleCall_0_1_0; }
		
		//CrossValidation
		public RuleCall getCrossValidationParserRuleCall_1() { return cCrossValidationParserRuleCall_1; }
	}
	public class ValidationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Validation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cValidationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPourcentageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPourcentageINTTerminalRuleCall_1_0 = (RuleCall)cPourcentageAssignment_1.eContents().get(0);
		
		//Validation:
		//	'Validation' pourcentage=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Validation' pourcentage=INT
		public Group getGroup() { return cGroup; }
		
		//'Validation'
		public Keyword getValidationKeyword_0() { return cValidationKeyword_0; }
		
		//pourcentage=INT
		public Assignment getPourcentageAssignment_1() { return cPourcentageAssignment_1; }
		
		//INT
		public RuleCall getPourcentageINTTerminalRuleCall_1_0() { return cPourcentageINTTerminalRuleCall_1_0; }
	}
	public class CrossValidationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.CrossValidation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCrossValidationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCrossValidationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cKAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cKINTTerminalRuleCall_2_0 = (RuleCall)cKAssignment_2.eContents().get(0);
		
		//CrossValidation:
		//	{CrossValidation} 'CrossValidation' k=INT?;
		@Override public ParserRule getRule() { return rule; }
		
		//{CrossValidation} 'CrossValidation' k=INT?
		public Group getGroup() { return cGroup; }
		
		//{CrossValidation}
		public Action getCrossValidationAction_0() { return cCrossValidationAction_0; }
		
		//'CrossValidation'
		public Keyword getCrossValidationKeyword_1() { return cCrossValidationKeyword_1; }
		
		//k=INT?
		public Assignment getKAssignment_2() { return cKAssignment_2; }
		
		//INT
		public RuleCall getKINTTerminalRuleCall_2_0() { return cKINTTerminalRuleCall_2_0; }
	}
	public class CibleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Cible");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCibleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cIdColonneParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Cible:
		//	'Cible' idColonne;
		@Override public ParserRule getRule() { return rule; }
		
		//'Cible' idColonne
		public Group getGroup() { return cGroup; }
		
		//'Cible'
		public Keyword getCibleKeyword_0() { return cCibleKeyword_0; }
		
		//idColonne
		public RuleCall getIdColonneParserRuleCall_1() { return cIdColonneParserRuleCall_1; }
	}
	public class PredictivesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Predictives");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPredictivesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPredictivesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPredictivesIdColonneParserRuleCall_1_0 = (RuleCall)cPredictivesAssignment_1.eContents().get(0);
		
		///* Colonne cible */ Predictives:
		//	'Predictives' predictives+=idColonne+;
		@Override public ParserRule getRule() { return rule; }
		
		//'Predictives' predictives+=idColonne+
		public Group getGroup() { return cGroup; }
		
		//'Predictives'
		public Keyword getPredictivesKeyword_0() { return cPredictivesKeyword_0; }
		
		//predictives+=idColonne+
		public Assignment getPredictivesAssignment_1() { return cPredictivesAssignment_1; }
		
		//idColonne
		public RuleCall getPredictivesIdColonneParserRuleCall_1_0() { return cPredictivesIdColonneParserRuleCall_1_0; }
	}
	public class IdColonneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.idColonne");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdINTTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		
		///* Colonnes prédictives */ idColonne:
		//	'Colonne' id=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Colonne' id=INT
		public Group getGroup() { return cGroup; }
		
		//'Colonne'
		public Keyword getColonneKeyword_0() { return cColonneKeyword_0; }
		
		//id=INT
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//INT
		public RuleCall getIdINTTerminalRuleCall_1_0() { return cIdINTTerminalRuleCall_1_0; }
	}
	public class AlgorithmeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Algorithme");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAlgorithmeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		///* id d'une colonne */ Algorithme:
		//	'Algorithme' text=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Algorithme' text=STRING
		public Group getGroup() { return cGroup; }
		
		//'Algorithme'
		public Keyword getAlgorithmeKeyword_0() { return cAlgorithmeKeyword_0; }
		
		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }
	}
	public class MetriqueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "src.idm_mml.MyDsl.Metrique");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMetriqueKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		///* Algo à utiliser */ Metrique:
		//	'Metrique' text=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Metrique' text=STRING
		public Group getGroup() { return cGroup; }
		
		//'Metrique'
		public Keyword getMetriqueKeyword_0() { return cMetriqueKeyword_0; }
		
		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }
	}
	
	
	private final MMLElements pMML;
	private final ImplementationElements pImplementation;
	private final DatasetElements pDataset;
	private final StrategieElements pStrategie;
	private final ValidationElements pValidation;
	private final CrossValidationElements pCrossValidation;
	private final CibleElements pCible;
	private final PredictivesElements pPredictives;
	private final IdColonneElements pIdColonne;
	private final AlgorithmeElements pAlgorithme;
	private final MetriqueElements pMetrique;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMML = new MMLElements();
		this.pImplementation = new ImplementationElements();
		this.pDataset = new DatasetElements();
		this.pStrategie = new StrategieElements();
		this.pValidation = new ValidationElements();
		this.pCrossValidation = new CrossValidationElements();
		this.pCible = new CibleElements();
		this.pPredictives = new PredictivesElements();
		this.pIdColonne = new IdColonneElements();
		this.pAlgorithme = new AlgorithmeElements();
		this.pMetrique = new MetriqueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("src.idm_mml.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MML:
	//	'MML' '{'
	//	mml+=Implementation+
	//	mml+=Dataset+
	//	'}';
	public MMLElements getMMLAccess() {
		return pMML;
	}
	
	public ParserRule getMMLRule() {
		return getMMLAccess().getRule();
	}
	
	//Implementation:
	//	{Implementation} 'Implementation' 'Scikit-learn' | 'Weka' '{'
	//	algo+=Algorithme
	//	metrique+=Metrique
	//	strategie+=Strategie
	//	'}';
	public ImplementationElements getImplementationAccess() {
		return pImplementation;
	}
	
	public ParserRule getImplementationRule() {
		return getImplementationAccess().getRule();
	}
	
	//Dataset:
	//	'Dataset' path=STRING '{'
	//	cible+=Cible
	//	predictives+=Predictives
	//	'}';
	public DatasetElements getDatasetAccess() {
		return pDataset;
	}
	
	public ParserRule getDatasetRule() {
		return getDatasetAccess().getRule();
	}
	
	//Strategie:
	//	'Strategie' strategie+=Validation | CrossValidation;
	public StrategieElements getStrategieAccess() {
		return pStrategie;
	}
	
	public ParserRule getStrategieRule() {
		return getStrategieAccess().getRule();
	}
	
	//Validation:
	//	'Validation' pourcentage=INT;
	public ValidationElements getValidationAccess() {
		return pValidation;
	}
	
	public ParserRule getValidationRule() {
		return getValidationAccess().getRule();
	}
	
	//CrossValidation:
	//	{CrossValidation} 'CrossValidation' k=INT?;
	public CrossValidationElements getCrossValidationAccess() {
		return pCrossValidation;
	}
	
	public ParserRule getCrossValidationRule() {
		return getCrossValidationAccess().getRule();
	}
	
	//Cible:
	//	'Cible' idColonne;
	public CibleElements getCibleAccess() {
		return pCible;
	}
	
	public ParserRule getCibleRule() {
		return getCibleAccess().getRule();
	}
	
	///* Colonne cible */ Predictives:
	//	'Predictives' predictives+=idColonne+;
	public PredictivesElements getPredictivesAccess() {
		return pPredictives;
	}
	
	public ParserRule getPredictivesRule() {
		return getPredictivesAccess().getRule();
	}
	
	///* Colonnes prédictives */ idColonne:
	//	'Colonne' id=INT;
	public IdColonneElements getIdColonneAccess() {
		return pIdColonne;
	}
	
	public ParserRule getIdColonneRule() {
		return getIdColonneAccess().getRule();
	}
	
	///* id d'une colonne */ Algorithme:
	//	'Algorithme' text=STRING;
	public AlgorithmeElements getAlgorithmeAccess() {
		return pAlgorithme;
	}
	
	public ParserRule getAlgorithmeRule() {
		return getAlgorithmeAccess().getRule();
	}
	
	///* Algo à utiliser */ Metrique:
	//	'Metrique' text=STRING;
	public MetriqueElements getMetriqueAccess() {
		return pMetrique;
	}
	
	public ParserRule getMetriqueRule() {
		return getMetriqueAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
