/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithme</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.Algorithme#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see src.idm_mml.mML.MMLPackage#getAlgorithme()
 * @model
 * @generated
 */
public interface Algorithme extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see src.idm_mml.mML.MMLPackage#getAlgorithme_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link src.idm_mml.mML.Algorithme#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // Algorithme
