/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cible</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see src.idm_mml.mML.MMLPackage#getCible()
 * @model
 * @generated
 */
public interface Cible extends EObject
{
} // Cible
