/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cross Validation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.CrossValidation#getK <em>K</em>}</li>
 * </ul>
 *
 * @see src.idm_mml.mML.MMLPackage#getCrossValidation()
 * @model
 * @generated
 */
public interface CrossValidation extends Strategie
{
  /**
   * Returns the value of the '<em><b>K</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>K</em>' attribute.
   * @see #setK(int)
   * @see src.idm_mml.mML.MMLPackage#getCrossValidation_K()
   * @model
   * @generated
   */
  int getK();

  /**
   * Sets the value of the '{@link src.idm_mml.mML.CrossValidation#getK <em>K</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>K</em>' attribute.
   * @see #getK()
   * @generated
   */
  void setK(int value);

} // CrossValidation
