/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>id Colonne</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.idColonne#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see src.idm_mml.mML.MMLPackage#getidColonne()
 * @model
 * @generated
 */
public interface idColonne extends Cible
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see src.idm_mml.mML.MMLPackage#getidColonne_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link src.idm_mml.mML.idColonne#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

} // idColonne
