/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Implementation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.Implementation#getAlgo <em>Algo</em>}</li>
 *   <li>{@link src.idm_mml.mML.Implementation#getMetrique <em>Metrique</em>}</li>
 *   <li>{@link src.idm_mml.mML.Implementation#getStrategie <em>Strategie</em>}</li>
 * </ul>
 *
 * @see src.idm_mml.mML.MMLPackage#getImplementation()
 * @model
 * @generated
 */
public interface Implementation extends EObject
{
  /**
   * Returns the value of the '<em><b>Algo</b></em>' containment reference list.
   * The list contents are of type {@link src.idm_mml.mML.Algorithme}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algo</em>' containment reference list.
   * @see src.idm_mml.mML.MMLPackage#getImplementation_Algo()
   * @model containment="true"
   * @generated
   */
  EList<Algorithme> getAlgo();

  /**
   * Returns the value of the '<em><b>Metrique</b></em>' containment reference list.
   * The list contents are of type {@link src.idm_mml.mML.Metrique}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metrique</em>' containment reference list.
   * @see src.idm_mml.mML.MMLPackage#getImplementation_Metrique()
   * @model containment="true"
   * @generated
   */
  EList<Metrique> getMetrique();

  /**
   * Returns the value of the '<em><b>Strategie</b></em>' containment reference list.
   * The list contents are of type {@link src.idm_mml.mML.Strategie}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategie</em>' containment reference list.
   * @see src.idm_mml.mML.MMLPackage#getImplementation_Strategie()
   * @model containment="true"
   * @generated
   */
  EList<Strategie> getStrategie();

} // Implementation
