/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MML</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.MML#getMml <em>Mml</em>}</li>
 * </ul>
 *
 * @see src.idm_mml.mML.MMLPackage#getMML()
 * @model
 * @generated
 */
public interface MML extends EObject
{
  /**
   * Returns the value of the '<em><b>Mml</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mml</em>' containment reference list.
   * @see src.idm_mml.mML.MMLPackage#getMML_Mml()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getMml();

} // MML
