/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see src.idm_mml.mML.MMLPackage
 * @generated
 */
public interface MMLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MMLFactory eINSTANCE = src.idm_mml.mML.impl.MMLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>MML</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MML</em>'.
   * @generated
   */
  MML createMML();

  /**
   * Returns a new object of class '<em>Implementation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Implementation</em>'.
   * @generated
   */
  Implementation createImplementation();

  /**
   * Returns a new object of class '<em>Dataset</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dataset</em>'.
   * @generated
   */
  Dataset createDataset();

  /**
   * Returns a new object of class '<em>Strategie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strategie</em>'.
   * @generated
   */
  Strategie createStrategie();

  /**
   * Returns a new object of class '<em>Validation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Validation</em>'.
   * @generated
   */
  Validation createValidation();

  /**
   * Returns a new object of class '<em>Cross Validation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cross Validation</em>'.
   * @generated
   */
  CrossValidation createCrossValidation();

  /**
   * Returns a new object of class '<em>Cible</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cible</em>'.
   * @generated
   */
  Cible createCible();

  /**
   * Returns a new object of class '<em>Predictives</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predictives</em>'.
   * @generated
   */
  Predictives createPredictives();

  /**
   * Returns a new object of class '<em>id Colonne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>id Colonne</em>'.
   * @generated
   */
  idColonne createidColonne();

  /**
   * Returns a new object of class '<em>Algorithme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithme</em>'.
   * @generated
   */
  Algorithme createAlgorithme();

  /**
   * Returns a new object of class '<em>Metrique</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metrique</em>'.
   * @generated
   */
  Metrique createMetrique();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MMLPackage getMMLPackage();

} //MMLFactory
