/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see src.idm_mml.mML.MMLFactory
 * @model kind="package"
 * @generated
 */
public interface MMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/MML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MMLPackage eINSTANCE = src.idm_mml.mML.impl.MMLPackageImpl.init();

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.MMLImpl <em>MML</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.MMLImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getMML()
   * @generated
   */
  int MML = 0;

  /**
   * The feature id for the '<em><b>Mml</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML__MML = 0;

  /**
   * The number of structural features of the '<em>MML</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.ImplementationImpl <em>Implementation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.ImplementationImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getImplementation()
   * @generated
   */
  int IMPLEMENTATION = 1;

  /**
   * The feature id for the '<em><b>Algo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLEMENTATION__ALGO = 0;

  /**
   * The feature id for the '<em><b>Metrique</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLEMENTATION__METRIQUE = 1;

  /**
   * The feature id for the '<em><b>Strategie</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLEMENTATION__STRATEGIE = 2;

  /**
   * The number of structural features of the '<em>Implementation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLEMENTATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.DatasetImpl <em>Dataset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.DatasetImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getDataset()
   * @generated
   */
  int DATASET = 2;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASET__PATH = 0;

  /**
   * The feature id for the '<em><b>Cible</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASET__CIBLE = 1;

  /**
   * The feature id for the '<em><b>Predictives</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASET__PREDICTIVES = 2;

  /**
   * The number of structural features of the '<em>Dataset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASET_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.StrategieImpl <em>Strategie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.StrategieImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getStrategie()
   * @generated
   */
  int STRATEGIE = 3;

  /**
   * The feature id for the '<em><b>Strategie</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGIE__STRATEGIE = 0;

  /**
   * The number of structural features of the '<em>Strategie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGIE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.ValidationImpl <em>Validation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.ValidationImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getValidation()
   * @generated
   */
  int VALIDATION = 4;

  /**
   * The feature id for the '<em><b>Pourcentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION__POURCENTAGE = 0;

  /**
   * The number of structural features of the '<em>Validation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.CrossValidationImpl <em>Cross Validation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.CrossValidationImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getCrossValidation()
   * @generated
   */
  int CROSS_VALIDATION = 5;

  /**
   * The feature id for the '<em><b>Strategie</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_VALIDATION__STRATEGIE = STRATEGIE__STRATEGIE;

  /**
   * The feature id for the '<em><b>K</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_VALIDATION__K = STRATEGIE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cross Validation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_VALIDATION_FEATURE_COUNT = STRATEGIE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.CibleImpl <em>Cible</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.CibleImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getCible()
   * @generated
   */
  int CIBLE = 6;

  /**
   * The number of structural features of the '<em>Cible</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIBLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.PredictivesImpl <em>Predictives</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.PredictivesImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getPredictives()
   * @generated
   */
  int PREDICTIVES = 7;

  /**
   * The feature id for the '<em><b>Predictives</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTIVES__PREDICTIVES = 0;

  /**
   * The number of structural features of the '<em>Predictives</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTIVES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.idColonneImpl <em>id Colonne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.idColonneImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getidColonne()
   * @generated
   */
  int ID_COLONNE = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_COLONNE__ID = CIBLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>id Colonne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_COLONNE_FEATURE_COUNT = CIBLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.AlgorithmeImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getAlgorithme()
   * @generated
   */
  int ALGORITHME = 9;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__TEXT = 0;

  /**
   * The number of structural features of the '<em>Algorithme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link src.idm_mml.mML.impl.MetriqueImpl <em>Metrique</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see src.idm_mml.mML.impl.MetriqueImpl
   * @see src.idm_mml.mML.impl.MMLPackageImpl#getMetrique()
   * @generated
   */
  int METRIQUE = 10;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIQUE__TEXT = 0;

  /**
   * The number of structural features of the '<em>Metrique</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIQUE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.MML <em>MML</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MML</em>'.
   * @see src.idm_mml.mML.MML
   * @generated
   */
  EClass getMML();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.MML#getMml <em>Mml</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mml</em>'.
   * @see src.idm_mml.mML.MML#getMml()
   * @see #getMML()
   * @generated
   */
  EReference getMML_Mml();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Implementation <em>Implementation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Implementation</em>'.
   * @see src.idm_mml.mML.Implementation
   * @generated
   */
  EClass getImplementation();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.Implementation#getAlgo <em>Algo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Algo</em>'.
   * @see src.idm_mml.mML.Implementation#getAlgo()
   * @see #getImplementation()
   * @generated
   */
  EReference getImplementation_Algo();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.Implementation#getMetrique <em>Metrique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metrique</em>'.
   * @see src.idm_mml.mML.Implementation#getMetrique()
   * @see #getImplementation()
   * @generated
   */
  EReference getImplementation_Metrique();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.Implementation#getStrategie <em>Strategie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Strategie</em>'.
   * @see src.idm_mml.mML.Implementation#getStrategie()
   * @see #getImplementation()
   * @generated
   */
  EReference getImplementation_Strategie();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Dataset <em>Dataset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dataset</em>'.
   * @see src.idm_mml.mML.Dataset
   * @generated
   */
  EClass getDataset();

  /**
   * Returns the meta object for the attribute '{@link src.idm_mml.mML.Dataset#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see src.idm_mml.mML.Dataset#getPath()
   * @see #getDataset()
   * @generated
   */
  EAttribute getDataset_Path();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.Dataset#getCible <em>Cible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cible</em>'.
   * @see src.idm_mml.mML.Dataset#getCible()
   * @see #getDataset()
   * @generated
   */
  EReference getDataset_Cible();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.Dataset#getPredictives <em>Predictives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predictives</em>'.
   * @see src.idm_mml.mML.Dataset#getPredictives()
   * @see #getDataset()
   * @generated
   */
  EReference getDataset_Predictives();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Strategie <em>Strategie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strategie</em>'.
   * @see src.idm_mml.mML.Strategie
   * @generated
   */
  EClass getStrategie();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.Strategie#getStrategie <em>Strategie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Strategie</em>'.
   * @see src.idm_mml.mML.Strategie#getStrategie()
   * @see #getStrategie()
   * @generated
   */
  EReference getStrategie_Strategie();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Validation <em>Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Validation</em>'.
   * @see src.idm_mml.mML.Validation
   * @generated
   */
  EClass getValidation();

  /**
   * Returns the meta object for the attribute '{@link src.idm_mml.mML.Validation#getPourcentage <em>Pourcentage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pourcentage</em>'.
   * @see src.idm_mml.mML.Validation#getPourcentage()
   * @see #getValidation()
   * @generated
   */
  EAttribute getValidation_Pourcentage();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.CrossValidation <em>Cross Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cross Validation</em>'.
   * @see src.idm_mml.mML.CrossValidation
   * @generated
   */
  EClass getCrossValidation();

  /**
   * Returns the meta object for the attribute '{@link src.idm_mml.mML.CrossValidation#getK <em>K</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>K</em>'.
   * @see src.idm_mml.mML.CrossValidation#getK()
   * @see #getCrossValidation()
   * @generated
   */
  EAttribute getCrossValidation_K();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Cible <em>Cible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cible</em>'.
   * @see src.idm_mml.mML.Cible
   * @generated
   */
  EClass getCible();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Predictives <em>Predictives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predictives</em>'.
   * @see src.idm_mml.mML.Predictives
   * @generated
   */
  EClass getPredictives();

  /**
   * Returns the meta object for the containment reference list '{@link src.idm_mml.mML.Predictives#getPredictives <em>Predictives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predictives</em>'.
   * @see src.idm_mml.mML.Predictives#getPredictives()
   * @see #getPredictives()
   * @generated
   */
  EReference getPredictives_Predictives();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.idColonne <em>id Colonne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>id Colonne</em>'.
   * @see src.idm_mml.mML.idColonne
   * @generated
   */
  EClass getidColonne();

  /**
   * Returns the meta object for the attribute '{@link src.idm_mml.mML.idColonne#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see src.idm_mml.mML.idColonne#getId()
   * @see #getidColonne()
   * @generated
   */
  EAttribute getidColonne_Id();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Algorithme <em>Algorithme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithme</em>'.
   * @see src.idm_mml.mML.Algorithme
   * @generated
   */
  EClass getAlgorithme();

  /**
   * Returns the meta object for the attribute '{@link src.idm_mml.mML.Algorithme#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see src.idm_mml.mML.Algorithme#getText()
   * @see #getAlgorithme()
   * @generated
   */
  EAttribute getAlgorithme_Text();

  /**
   * Returns the meta object for class '{@link src.idm_mml.mML.Metrique <em>Metrique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metrique</em>'.
   * @see src.idm_mml.mML.Metrique
   * @generated
   */
  EClass getMetrique();

  /**
   * Returns the meta object for the attribute '{@link src.idm_mml.mML.Metrique#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see src.idm_mml.mML.Metrique#getText()
   * @see #getMetrique()
   * @generated
   */
  EAttribute getMetrique_Text();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MMLFactory getMMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.MMLImpl <em>MML</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.MMLImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getMML()
     * @generated
     */
    EClass MML = eINSTANCE.getMML();

    /**
     * The meta object literal for the '<em><b>Mml</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML__MML = eINSTANCE.getMML_Mml();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.ImplementationImpl <em>Implementation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.ImplementationImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getImplementation()
     * @generated
     */
    EClass IMPLEMENTATION = eINSTANCE.getImplementation();

    /**
     * The meta object literal for the '<em><b>Algo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLEMENTATION__ALGO = eINSTANCE.getImplementation_Algo();

    /**
     * The meta object literal for the '<em><b>Metrique</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLEMENTATION__METRIQUE = eINSTANCE.getImplementation_Metrique();

    /**
     * The meta object literal for the '<em><b>Strategie</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLEMENTATION__STRATEGIE = eINSTANCE.getImplementation_Strategie();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.DatasetImpl <em>Dataset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.DatasetImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getDataset()
     * @generated
     */
    EClass DATASET = eINSTANCE.getDataset();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATASET__PATH = eINSTANCE.getDataset_Path();

    /**
     * The meta object literal for the '<em><b>Cible</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATASET__CIBLE = eINSTANCE.getDataset_Cible();

    /**
     * The meta object literal for the '<em><b>Predictives</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATASET__PREDICTIVES = eINSTANCE.getDataset_Predictives();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.StrategieImpl <em>Strategie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.StrategieImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getStrategie()
     * @generated
     */
    EClass STRATEGIE = eINSTANCE.getStrategie();

    /**
     * The meta object literal for the '<em><b>Strategie</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRATEGIE__STRATEGIE = eINSTANCE.getStrategie_Strategie();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.ValidationImpl <em>Validation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.ValidationImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getValidation()
     * @generated
     */
    EClass VALIDATION = eINSTANCE.getValidation();

    /**
     * The meta object literal for the '<em><b>Pourcentage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATION__POURCENTAGE = eINSTANCE.getValidation_Pourcentage();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.CrossValidationImpl <em>Cross Validation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.CrossValidationImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getCrossValidation()
     * @generated
     */
    EClass CROSS_VALIDATION = eINSTANCE.getCrossValidation();

    /**
     * The meta object literal for the '<em><b>K</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CROSS_VALIDATION__K = eINSTANCE.getCrossValidation_K();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.CibleImpl <em>Cible</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.CibleImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getCible()
     * @generated
     */
    EClass CIBLE = eINSTANCE.getCible();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.PredictivesImpl <em>Predictives</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.PredictivesImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getPredictives()
     * @generated
     */
    EClass PREDICTIVES = eINSTANCE.getPredictives();

    /**
     * The meta object literal for the '<em><b>Predictives</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICTIVES__PREDICTIVES = eINSTANCE.getPredictives_Predictives();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.idColonneImpl <em>id Colonne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.idColonneImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getidColonne()
     * @generated
     */
    EClass ID_COLONNE = eINSTANCE.getidColonne();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ID_COLONNE__ID = eINSTANCE.getidColonne_Id();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.AlgorithmeImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getAlgorithme()
     * @generated
     */
    EClass ALGORITHME = eINSTANCE.getAlgorithme();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHME__TEXT = eINSTANCE.getAlgorithme_Text();

    /**
     * The meta object literal for the '{@link src.idm_mml.mML.impl.MetriqueImpl <em>Metrique</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see src.idm_mml.mML.impl.MetriqueImpl
     * @see src.idm_mml.mML.impl.MMLPackageImpl#getMetrique()
     * @generated
     */
    EClass METRIQUE = eINSTANCE.getMetrique();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIQUE__TEXT = eINSTANCE.getMetrique_Text();

  }

} //MMLPackage
