/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Strategie</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.Strategie#getStrategie <em>Strategie</em>}</li>
 * </ul>
 *
 * @see src.idm_mml.mML.MMLPackage#getStrategie()
 * @model
 * @generated
 */
public interface Strategie extends EObject
{
  /**
   * Returns the value of the '<em><b>Strategie</b></em>' containment reference list.
   * The list contents are of type {@link src.idm_mml.mML.Validation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategie</em>' containment reference list.
   * @see src.idm_mml.mML.MMLPackage#getStrategie_Strategie()
   * @model containment="true"
   * @generated
   */
  EList<Validation> getStrategie();

} // Strategie
