/**
 * generated by Xtext 2.19.0
 */
package src.idm_mml.mML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Validation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link src.idm_mml.mML.Validation#getPourcentage <em>Pourcentage</em>}</li>
 * </ul>
 *
 * @see src.idm_mml.mML.MMLPackage#getValidation()
 * @model
 * @generated
 */
public interface Validation extends EObject
{
  /**
   * Returns the value of the '<em><b>Pourcentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pourcentage</em>' attribute.
   * @see #setPourcentage(int)
   * @see src.idm_mml.mML.MMLPackage#getValidation_Pourcentage()
   * @model
   * @generated
   */
  int getPourcentage();

  /**
   * Sets the value of the '{@link src.idm_mml.mML.Validation#getPourcentage <em>Pourcentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pourcentage</em>' attribute.
   * @see #getPourcentage()
   * @generated
   */
  void setPourcentage(int value);

} // Validation
