/*
 * generated by Xtext 2.19.0
 */
package src.idm_mml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
