/*
 * generated by Xtext 2.19.0
 */
package src.idm_mml.ui;

import com.google.inject.Injector;
import idm_mml.ui.internal.Idm_mmlActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Idm_mmlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Idm_mmlActivator activator = Idm_mmlActivator.getInstance();
		return activator != null ? activator.getInjector(Idm_mmlActivator.SRC_IDM_MML_MYDSL) : null;
	}

}
